### PR TITLE
Add frequency seekbar. 

### PR DESCRIPTION
**Pull request by souch**
This pull request add the following features :
- frequency seekbar
- "Logarithmic" like Seekbar
- add button to increase accuracy

Increase version to 1.3.

Hope you like it.

### CODE REVIEW

**Comment by stwalkerster** [comment]
Awesome, thanks!

This looks good overall, but I'd rather not bump the version number quite yet until this is good for release. I'm also not so sure about the frequency bar - Android is not a RTOS, so it can't guarantee that it'll respect a specific frequency. I wonder if adding some help may be a good idea?

The other concern I have is the layout of the main window now - have you tested it on a few different screen sizes? The enable button looks a little squished on my phone (oneplus one):

screen

**Comment by souch** [comment]
Yes this pull request is not perfect, but I like the fact to know what is the current frequency. I don't need nor have the time to make a better GUI (logarithmic precision could be better, +- button could react on long tap...).

For sure Android is not realtime, but I guess the worst is the flash light (at least mine) which can't handle sthg more than 30Hz. It isn't meant to be very precise (yes, we could remove the decimal precision...). But in the future with hardware enhancement, even if android is not RTOS it is possible that the flash and the OS could be quite precise until 100Hz. Perhaps I am wrong, I will investigate more on this.

For the layout on my phone it is even more squished:-), but I have an old 3.5" so I though anyone would have a bigger screen and it would not be squished. My bad. I can fix this pb I think.

Postpone the new version is wise :-), I'll have a look at these as soon as possible.

**Comment by souch** [comment]
thanks

**Comment by stwalkerster** [comment]
I'm digging through the UI now, trying to have a think about how the interface could be tidied up a little bit - trying to relearn Android layout stuff, as I've not touched it in years (and I keep thinking of WPF solutions!)

Thanks again for the PR! :grinning:

**Comment by souch** [comment]
I will do it if you want. I know how to already I think.

**Pull request merged**
